// src/pages/Detail.jsx
import { useNavigate, useParams, Link } from 'react-router-dom';
import { ChevronLeft, Heart, Share2, Download, Check, Image as ImageIcon, Info, Smartphone, Monitor, User, Layers } from 'lucide-react';
import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import PreviewOverlay from '../components/PreviewOverlay';

export default function Detail() {
    const navigate = useNavigate();
    const { id } = useParams();
    const [image, setImage] = useState(null);
    const [related, setRelated] = useState([]);
    const [showModal, setShowModal] = useState(false);
    const [loading, setLoading] = useState(true);
    const [isLiked, setIsLiked] = useState(false);
    const [previewType, setPreviewType] = useState(null); // 'mobile', 'pc', 'avatar', null

    useEffect(() => {
        setLoading(true);
        fetch(`/api/wallpapers/${id}`)
            .then(res => res.json())
            .then(async data => {
                setImage(data);
                recordHistory(data);

                // Fetch Recommendations (4 from tags, 2 from categories)
                try {
                    const tagNames = data.tags.map(t => t.name).join(',');
                    const catNames = data.categories.map(c => c.name).join(',');

                    const [tagRes, catRes] = await Promise.all([
                        fetch(`/api/wallpapers?tags=${tagNames}&limit=10`),
                        fetch(`/api/wallpapers?categories=${catNames}&limit=10`)
                    ]);

                    const tagRelated = tagRes.ok ? await tagRes.json() : [];
                    const catRelated = catRes.ok ? await catRes.json() : [];

                    // 4+2 logic
                    const fromTags = tagRelated.filter(t => t.id !== data.id).slice(0, 4);
                    const fromCats = catRelated
                        .filter(c => c.id !== data.id && !fromTags.some(t => t.id === c.id))
                        .slice(0, 2);

                    setRelated([...fromTags, ...fromCats]);
                } catch (err) {
                    console.error('Failed to fetch recommendations', err);
                }

                setLoading(false);
            })
            .catch(err => {
                console.error(err);
                setLoading(false);
            });
    }, [id]);

    const recordHistory = async (img) => {
        if (!img) return;

        const qutu_user = JSON.parse(localStorage.getItem('qutu_user') || '{}');
        const userId = qutu_user.id;

        // Local storage record
        const history = JSON.parse(localStorage.getItem('qutu_history') || '[]');
        const filtered = history.filter(item => item.id !== img.id);
        const newHistory = [{
            id: img.id,
            thumb: img.thumb,
            title: img.title,
            time: new Date().getTime()
        }, ...filtered].slice(0, 50);
        localStorage.setItem('qutu_history', JSON.stringify(newHistory));

        // Cloud sync if logged in
        if (userId) {
            try {
                await fetch('/api/interactions/history', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ userId, imageId: img.id })
                });
            } catch (err) {
                console.error('Failed to sync history', err);
            }
        }
    };

    const handleDownload = () => {
        // In a real local dev, image.url might be /uploads/xxx.
        // We'll just open it in a new tab.
        window.open(image.url, '_blank');
        setShowModal(true);
    };

    if (loading) return (
        <div className="h-screen bg-black flex items-center justify-center text-white">
            <div className="w-8 h-8 border-2 border-white/20 border-t-white rounded-full animate-spin"></div>
        </div>
    );
    if (!image) return (
        <div className="h-screen bg-black flex items-center justify-center text-white font-bold tracking-widest uppercase">
            Pixel Lost
        </div>
    );

    return (
        <div className="min-h-screen w-full bg-black relative flex flex-col pb-10">
            {/* 沉浸式顶部 */}
            <div className="absolute top-0 w-full pt-14 px-4 z-40 flex justify-between items-center pointer-events-none">
                <div
                    onClick={() => navigate(-1)}
                    className="w-10 h-10 bg-black/20 backdrop-blur-xl rounded-full flex items-center justify-center text-white cursor-pointer pointer-events-auto active:scale-90 transition"
                >
                    <ChevronLeft size={24} />
                </div>
            </div>

            {/* Main Image Container (Changed to responsive) */}
            <div className="w-full min-h-[50vh] max-h-[75vh] flex items-center justify-center p-4 shrink-0 overflow-hidden">
                <motion.img
                    layoutId={`img-${image.id}`}
                    src={image.url}
                    className="w-full max-h-full object-contain rounded-3xl"
                    alt={image.title}
                />
            </div>

            {/* 信息面板 (不再绝对定位，适应图片高度) */}
            <div className="px-6 pb-20 pt-4 flex-1">
                <div className="bg-white/5 backdrop-blur-2xl rounded-[32px] p-8 border border-white/10 shadow-2xl">
                    {/* 信息面板 */}
                    <div className="mb-8 space-y-4">
                        <div className="space-y-4">
                            <h2 className="text-white text-3xl font-black tracking-tight leading-tight">{image.title}</h2>

                            {/* Improved Author Section - Below Title */}
                            <div className="flex items-center gap-4 py-2">
                                <Link to={`/profile/${image.author?.id}`} className="flex items-center gap-2.5 group">
                                    <div className="w-8 h-8 rounded-full overflow-hidden border border-white/10 ring-2 ring-white/5 group-hover:ring-indigo-500/50 transition-all">
                                        <img
                                            src={image.author?.avatar || "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=100&q=80"}
                                            className="w-full h-full object-cover"
                                            alt="author"
                                        />
                                    </div>
                                    <div>
                                        <div className="text-white text-[13px] font-black group-hover:text-indigo-400 transition-colors uppercase tracking-wide">{image.author?.nickname || "未名画师"}</div>
                                        <div className="text-[8px] text-gray-500 font-bold uppercase tracking-[0.15em] mt-0.5 flex items-center gap-1.5">
                                            <span className="w-1 h-1 rounded-full bg-indigo-500"></span>
                                            Verified Artist
                                        </div>
                                    </div>
                                </Link>
                                <div className="h-4 w-px bg-white/10 mx-2"></div>
                                <p className="text-gray-500 text-[9px] font-bold uppercase tracking-widest leading-none">
                                    {new Date(image.createdAt).toLocaleDateString()}
                                </p>
                            </div>
                        </div>

                        {/* 分类与标签 (移动到描述上方，支持展开/收起) */}
                        <ExpandableTags categories={image.categories} tags={image.tags} />
                    </div>

                    {/* 图片描述 (移动到标签下方) */}
                    {image.description && (
                        <div className="flex items-start gap-2 bg-white/5 backdrop-blur-md rounded-2xl p-4 border border-white/10 mt-6 min-h-[80px]">
                            <Info size={14} className="text-purple-400 mt-0.5 shrink-0" />
                            <p className="text-gray-200 text-xs leading-relaxed font-medium">
                                {image.description}
                            </p>
                        </div>
                    )}
                </div>

                {/* 操作按钮 */}
                <div className="flex flex-col gap-4">
                    <div className="flex gap-4">
                        <button
                            onClick={() => setPreviewType('mobile')}
                            className="flex-1 bg-white/10 backdrop-blur-xl border border-white/10 text-white h-12 rounded-xl font-bold text-[10px] uppercase tracking-widest flex items-center justify-center gap-2 active:scale-95 transition"
                        >
                            <Smartphone size={14} /> 手机预览
                        </button>
                        <button
                            onClick={() => setPreviewType('pc')}
                            className="flex-1 bg-white/10 backdrop-blur-xl border border-white/10 text-white h-12 rounded-xl font-bold text-[10px] uppercase tracking-widest flex items-center justify-center gap-2 active:scale-95 transition"
                        >
                            <Monitor size={14} /> 电脑预览
                        </button>
                        <button
                            onClick={() => setPreviewType('avatar')}
                            className="flex-1 bg-white/10 backdrop-blur-xl border border-white/10 text-white h-12 rounded-xl font-bold text-[10px] uppercase tracking-widest flex items-center justify-center gap-2 active:scale-95 transition"
                        >
                            <User size={14} /> 头像预览
                        </button>
                    </div>

                    <div className="flex justify-between items-center gap-4">
                        <button
                            onClick={handleDownload}
                            className="flex-1 bg-white text-gray-900 h-14 rounded-2xl font-black text-sm uppercase tracking-[0.2em] flex items-center justify-center gap-3 hover:bg-gray-100 active:scale-[0.98] transition shadow-2xl shadow-indigo-500/10"
                        >
                            <Download size={20} />
                            下载原图
                        </button>
                    </div>
                </div>

                {/* Related Images Section */}
                {
                    related.length > 0 && (
                        <div className="px-6 py-10 bg-black">
                            <div className="flex items-center justify-between mb-6">
                                <h3 className="text-white font-black flex items-center text-[10px] uppercase tracking-[0.25em]">
                                    <ImageIcon size={14} className="mr-3 text-indigo-400" />
                                    相关推荐
                                </h3>
                                <div className="h-px flex-1 mx-4 bg-white/10"></div>
                            </div>
                            <div className="grid grid-cols-3 gap-3">
                                {related.map(item => (
                                    <Link to={`/detail/${item.id}`} key={item.id} className="aspect-[3/4] rounded-xl overflow-hidden relative active:scale-95 transition group">
                                        <img src={item.thumb} alt={item.title} className="w-full h-full object-cover group-hover:scale-110 transition duration-500" loading="lazy" />
                                        <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                                    </Link>
                                ))}
                            </div>
                        </div>
                    )
                }

                {/* Preview Overlay */}
                <AnimatePresence>
                    {previewType && (
                        <PreviewOverlay
                            type={previewType}
                            imageSrc={image.url}
                            onClose={() => setPreviewType(null)}
                        />
                    )}
                </AnimatePresence>

                {/* Download Success Modal */}
                <AnimatePresence>
                    {showModal && (
                        <div className="fixed inset-0 z-50 flex items-center justify-center p-6">
                            <motion.div
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                onClick={() => setShowModal(false)}
                                className="absolute inset-0 bg-black/80 backdrop-blur-md"
                            />

                            <motion.div
                                initial={{ scale: 0.9, opacity: 0, y: 20 }}
                                animate={{ scale: 1, opacity: 1, y: 0 }}
                                exit={{ scale: 0.9, opacity: 0, y: 20 }}
                                className="bg-white rounded-[32px] p-8 flex flex-col items-center w-full max-w-sm relative z-10"
                            >
                                <div className="w-20 h-20 bg-green-50 rounded-full flex items-center justify-center text-green-500 mb-6">
                                    <Check size={40} />
                                </div>
                                <h3 className="font-black text-gray-900 text-xl mb-2 tracking-tight">保存成功</h3>
                                <p className="text-center text-gray-400 text-sm font-medium mb-8">高清像素已在您的下载任务中，快去设为壁纸吧！</p>

                                <div className="flex flex-col w-full gap-3">
                                    <button
                                        onClick={() => navigate(-1)}
                                        className="w-full py-4 rounded-2xl bg-black text-white text-sm font-black uppercase tracking-widest active:scale-95 transition"
                                    >
                                        返回发现列表
                                    </button>
                                    <button
                                        onClick={() => setShowModal(false)}
                                        className="w-full py-4 rounded-2xl border border-gray-100 text-gray-400 text-sm font-black uppercase tracking-widest active:bg-gray-50 transition"
                                    >
                                        留在本页
                                    </button>
                                </div>
                            </motion.div>
                        </div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
}

function ExpandableTags({ categories = [], tags = [] }) {
    const [expanded, setExpanded] = useState(false);
    const limit = 6;

    // Merge categories and tags for unified limiting
    const allItems = [
        ...categories.map(c => ({ type: 'category', ...c })),
        ...tags.map(t => ({ type: 'tag', ...t }))
    ];

    const hasMore = allItems.length > limit;
    const displayItems = expanded ? allItems : allItems.slice(0, limit);

    return (
        <div className="flex flex-col gap-3">
            <div className="flex gap-2 flex-wrap mb-2">
                {displayItems.map((item, idx) => (
                    item.type === 'category'
                        ? <CategoryTag key={`cat-${item.id}`} text={item.name} />
                        : <Tag key={`tag-${item.id}`} text={`#${item.name}`} />
                ))}

                {hasMore && (
                    <button
                        onClick={() => setExpanded(!expanded)}
                        className="bg-white/5 backdrop-blur-md text-indigo-300 px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest border border-indigo-400/20 active:scale-95 transition"
                    >
                        {expanded ? '收起' : `展开+${allItems.length - limit}`}
                    </button>
                )}
            </div>
        </div>
    );
}

function Tag({ text }) {
    return <span className="bg-white/5 backdrop-blur-md text-white/60 px-4 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-widest border border-white/5">{text}</span>
}

function CategoryTag({ text }) {
    return <span className="bg-indigo-600/30 backdrop-blur-md text-white px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest border border-indigo-400/20">{text}</span>
}

function CircleBtn({ icon, activeColor, onClick }) {
    return (
        <button
            onClick={onClick}
            className={`w-14 h-14 bg-white/10 backdrop-blur-xl rounded-full flex items-center justify-center text-white border border-white/10 active:scale-90 transition transform ${activeColor}`}
        >
            {icon}
        </button>
    )
}

// src/pages/ai/detail.vue
<template>
  <view v-if="loading" class="h-screen bg-black flex flex-col items-center justify-center text-white gap-4">
    <text class="animate-spin text-indigo-500 text-2xl">↻</text>
    <text class="text-[10px] font-black uppercase tracking-[0.3em] opacity-40">Retrieving Neural Record</text>
  </view>
  <view v-else-if="!task" class="h-screen bg-black flex items-center justify-center text-white font-black tracking-[0.5em] uppercase text-center px-10">
    Record Not Found
  </view>
  <view v-else class="min-h-screen w-full bg-black relative flex flex-col pb-24 selection:bg-indigo-500">
    <!-- Header -->
    <view class="w-full flex justify-between items-center px-6 py-4 bg-black border-b border-white/5">
      <view
        @tap="goBack"
        class="w-10 h-10 bg-white/5 border border-white/10 rounded-xl flex items-center justify-center text-white active:scale-95 transition"
      >
        <text>←</text>
      </view>
    </view>

    <!-- Main Image -->
    <view class="w-full flex-1 flex items-center justify-center p-6 min-h-[60vh] relative">
      <image
        :src="task.resultUrl"
        mode="aspectFit"
        class="max-w-full max-h-[80vh] rounded-[32px] shadow-2xl"
      />
    </view>

    <!-- Previews -->
    <view class="flex gap-3 px-6 py-2">
      <view @tap="setPreview('mobile')" class="flex-1 bg-white/5 border border-white/10 text-white h-12 rounded-2xl font-bold text-[9px] uppercase tracking-widest flex items-center justify-center gap-2 active:scale-95 transition">
        手机预览
      </view>
      <view @tap="setPreview('pc')" class="flex-1 bg-white/5 border border-white/10 text-white h-12 rounded-2xl font-bold text-[9px] uppercase tracking-widest flex items-center justify-center gap-2 active:scale-95 transition">
        电脑预览
      </view>
      <view @tap="setPreview('avatar')" class="flex-1 bg-white/5 border border-white/10 text-white h-12 rounded-2xl font-bold text-[9px] uppercase tracking-widest flex items-center justify-center gap-2 active:scale-95 transition">
        头像预览
      </view>
    </view>

    <!-- Info Panel -->
    <view class="px-6 space-y-4">
      <view class="bg-white/5 backdrop-blur-3xl rounded-[32px] p-8 border border-white/10 shadow-2xl">
        <view class="flex items-center justify-between mb-6">
          <view>
            <view class="flex items-center gap-2.5 mb-2">
              <text class="px-2.5 py-0.5 bg-indigo-500 rounded text-[8px] font-black text-white uppercase tracking-widest">
                {{ task.model }}
              </text>
              <text class="text-[8px] font-bold text-gray-500 uppercase tracking-widest">
                {{ formatDate(task.createdAt) }}
              </text>
            </view>
            <text class="text-white text-2xl font-black tracking-tight leading-tight block">AI 创作详情</text>
          </view>
        </view>

        <!-- Prompt Box -->
        <view class="bg-white/5 rounded-2xl p-5 border border-white/5 relative group">
          <view class="flex items-center gap-2 mb-2">
            <text class="text-indigo-400 text-xs">✨</text>
            <text class="text-[9px] font-black text-gray-400 uppercase tracking-widest">Prompt Logic</text>
          </view>
          <text class="text-gray-200 text-xs leading-relaxed font-medium italic block">
            "{{ task.prompt }}"
          </text>
        </view>
      </view>

      <view class="flex gap-4">
        <view
          @tap="handleDownload"
          class="flex-1 bg-white text-gray-900 h-16 rounded-[24px] font-black text-sm uppercase tracking-[0.2em] flex items-center justify-center gap-3 active:scale-[0.98] transition shadow-2xl shadow-indigo-500/10"
        >
          下载原图
        </view>
        <view
          @tap="openSubmit"
          class="flex-1 bg-indigo-600 text-white h-16 rounded-[24px] font-black text-sm uppercase tracking-[0.2em] flex items-center justify-center gap-3 active:scale-[0.98] transition shadow-2xl shadow-indigo-500/20"
        >
          发布至画廊
        </view>
      </view>
      
      <view @tap="handleDelete" class="w-full py-4 text-center mt-4">
        <text class="text-red-500/50 text-[10px] font-bold uppercase tracking-widest">删除此项记录</text>
      </view>
    </view>

    <!-- Submit Modal -->
    <view v-if="showSubmitModal" class="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/80 backdrop-blur-md">
      <view class="bg-white w-full max-w-lg rounded-[40px] overflow-hidden shadow-2xl p-10 flex flex-col relative">
        <view @tap="showSubmitModal = false" class="absolute right-8 top-8 p-2 text-gray-300">
           ✕
        </view>

        <view class="mb-10 text-center">
          <text class="text-2xl font-black text-gray-900 tracking-tight block">发布作品审核</text>
          <text class="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-1 block">Share Your Creation with the World</text>
        </view>

        <view class="space-y-8">
          <view class="space-y-2">
            <text class="text-[10px] font-black text-gray-400 uppercase tracking-widest ml-1 block">作品标题</text>
            <input
              v-model="formData.title"
              class="w-full p-5 bg-gray-50 border border-gray-100 rounded-2xl text-sm font-bold"
              placeholder="Enter artwork title..."
            />
          </view>

          <view class="space-y-2">
            <text class="text-[10px] font-black text-gray-400 uppercase tracking-widest ml-1 block">作品分类</text>
            <view class="flex flex-wrap gap-2">
              <view
                v-for="cat in categories"
                :key="cat.id"
                @tap="toggleCategory(cat.name)"
                :class="['px-5 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all', (formData.categories || '').split(',').includes(cat.name) ? 'bg-indigo-600 text-white' : 'bg-gray-50 text-gray-400']"
              >
                {{ cat.name }}
              </view>
            </view>
          </view>

          <view class="pt-6 flex gap-4">
            <view @tap="showSubmitModal = false" class="px-8 py-5 rounded-2xl text-[11px] font-black uppercase tracking-widest bg-gray-50 text-gray-400">
              取消
            </view>
            <view
              @tap="submitForReview"
              :class="['flex-1 py-5 rounded-2xl text-[11px] font-black text-white text-center uppercase tracking-[0.2em] shadow-xl transition-all', submitLoading ? 'bg-gray-400 opacity-50' : 'bg-gray-900']"
            >
              {{ submitLoading ? '提交中...' : '确认发布' }}
            </view>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { aiService, categoriesService, tagsService } from '../../services/api';

const id = ref(null);
const task = ref(null);
const loading = ref(true);
const showSubmitModal = ref(false);
const submitLoading = ref(false);
const categories = ref([]);
const tags = ref([]);
const formData = ref({
  title: '',
  categories: '',
  tags: '',
  description: ''
});

onLoad((options) => {
  id.value = options.id;
});

const fetchTask = async () => {
  if (!id.value) return;
  loading.value = true;
  try {
    const data = await aiService.getTaskStatus(id.value);
    task.value = data;
    formData.value.title = `AI 创作 - ${new Date(data.createdAt).toLocaleDateString()}`;
    formData.value.description = data.prompt;
  } catch (err) {
    console.error('Fetch task failed', err);
  } finally {
    loading.value = false;
  }
};

const fetchMetadata = async () => {
  try {
    const [cats, tgs] = await Promise.all([
      categoriesService.findAll(),
      tagsService.findAll()
    ]);
    categories.value = cats || [];
    tags.value = tgs || [];
  } catch (err) {
    console.error('Fetch metadata failed', err);
  }
};

const handleDownload = () => {
  if (!task.value?.resultUrl) return;
  uni.setClipboardData({
    data: task.value.resultUrl,
    success: () => {
      uni.showToast({ title: '链接已复制', icon: 'none' });
    }
  });
};

const handleDelete = () => {
  uni.showModal({
    title: '确认删除',
    content: '确定要删除这张创作吗？此操作无法撤销。',
    success: async (res) => {
      if (res.confirm) {
        try {
          await aiService.deleteTask(id.value);
          uni.navigateBack();
        } catch (err) {
          uni.showToast({ title: '删除失败', icon: 'none' });
        }
      }
    }
  });
};

const openSubmit = () => {
  showSubmitModal.value = true;
  fetchMetadata();
};

const toggleCategory = (name) => {
  const current = formData.value.categories ? formData.value.categories.split(',').filter(Boolean) : [];
  if (current.includes(name)) {
    formData.value.categories = current.filter(n => n !== name).join(',');
  } else {
    formData.value.categories = [...current, name].join(',');
  }
};

const submitForReview = async () => {
  if (!formData.value.categories) {
    uni.showToast({ title: '请选择分类', icon: 'none' });
    return;
  }
  submitLoading.value = true;
  try {
    await aiService.submitToGallery({
      taskId: id.value,
      ...formData.value
    });
    uni.showToast({ title: '提交成功' });
    showSubmitModal.value = false;
  } catch (err) {
    uni.showToast({ title: '提交失败', icon: 'none' });
  } finally {
    submitLoading.value = false;
  }
};

const goBack = () => uni.navigateBack();
const formatDate = (date) => new Date(date).toLocaleString();
const setPreview = (type) => uni.showToast({ title: `${type}预览开发中`, icon: 'none' });

onMounted(fetchTask);
</script>

<style scoped>
.animate-spin {
  animation: spin 1s linear infinite;
}
@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
</style>
