// src/pages/upload/upload.vue
<template>
  <view class="bg-white dark:bg-black min-h-screen pb-24 transition-colors duration-300">
    <!-- Header -->
    <view class="pt-12 px-6 pb-4 flex items-center justify-between sticky top-0 z-40 bg-white/80 dark:bg-black/80 backdrop-blur-md">
      <view @tap="goBack" class="w-10 h-10 -ml-2 flex items-center justify-center active:scale-90 transition-all text-gray-900 dark:text-white">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg>
      </view>
      <text class="text-lg font-bold text-gray-900 dark:text-white tracking-wide">发布壁纸</text>
      <view class="w-8"></view>
    </view>

    <scroll-view scroll-y class="h-screen" :show-scrollbar="false">
       <view class="px-6 pb-40">
         
         <!-- Upload Area -->
         <view class="mt-4 mb-10 group">
           <view 
             class="w-full aspect-[4/5] rounded-3xl border-2 border-dashed border-gray-300 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-900/50 flex flex-col items-center justify-center transition-all active:scale-[0.98]"
             :class="{'border-gray-900 dark:border-white': imagePath}"
             @tap="chooseImage"
           >
             <image v-if="imagePath" :src="imagePath" mode="aspectFit" class="w-full h-full rounded-3xl" />
             <view v-else class="flex flex-col items-center gap-4 p-8 text-center">
                <view class="w-16 h-16 rounded-full bg-white dark:bg-zinc-800 shadow-sm flex items-center justify-center text-gray-400 dark:text-gray-500 mb-2 group-hover:scale-110 transition-transform duration-300">
                   <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>
                </view>
                <text class="text-sm font-bold text-gray-500 dark:text-gray-400">点击上传图片</text>
                <text class="text-xs text-gray-400 dark:text-gray-600">支持 JPG, PNG (最大 10MB)</text>
             </view>
           </view>
           <view v-if="imagePath" class="mt-4 flex justify-center">
             <text class="text-xs text-gray-400 underline" @tap.stop="imagePath = ''">移除图片</text>
           </view>
         </view>

         <!-- Form Fields -->
         <view class="space-y-8">
            <!-- Title -->
            <view>
              <text class="block text-xs font-bold uppercase tracking-wider text-gray-400 mb-2">标题</text>
              <input 
                type="text" 
                v-model="form.title"
                placeholder="给你的壁纸起个名字" 
                placeholder-class="text-gray-300 dark:text-gray-700"
                class="w-full py-3 border-b border-gray-200 dark:border-zinc-800 text-lg font-medium text-gray-900 dark:text-white focus:border-black dark:focus:border-white transition-colors bg-transparent"
              />
            </view>

             <!-- Category -->
            <view>
              <text class="block text-xs font-bold uppercase tracking-wider text-gray-400 mb-2">分类</text>
              <picker mode="selector" :range="categories" @change="handleCategoryChange">
                 <view class="w-full py-3 border-b border-gray-200 dark:border-zinc-800 flex justify-between items-center">
                   <text :class="form.category ? 'text-gray-900 dark:text-white' : 'text-gray-300 dark:text-gray-700'" class="text-lg font-medium">
                     {{ form.category || '选择分类' }}
                   </text>
                   <text class="text-gray-400">></text>
                 </view>
              </picker>
            </view>

             <!-- Tags -->
            <view>
              <text class="block text-xs font-bold uppercase tracking-wider text-gray-400 mb-2">标签</text>
              <view class="flex flex-wrap gap-2 mb-3">
                 <view 
                   v-for="tag in commonTags" 
                   :key="tag"
                   class="px-3 py-1.5 rounded-full text-xs font-medium border transition-colors cursor-pointer active:scale-95"
                   :class="form.tags.includes(tag) ? 'bg-black dark:bg-white text-white dark:text-black border-transparent' : 'bg-transparent border-gray-200 dark:border-zinc-700 text-gray-500 dark:text-gray-400'"
                   @tap="toggleTag(tag)"
                 >
                   #{{ tag }}
                 </view>
              </view>
            </view>

            <!-- Description -->
             <view>
              <text class="block text-xs font-bold uppercase tracking-wider text-gray-400 mb-2">描述</text>
              <textarea 
                v-model="form.description"
                placeholder="介绍一下这个作品..." 
                placeholder-class="text-gray-300 dark:text-gray-700"
                class="w-full h-24 py-3 border-b border-gray-200 dark:border-zinc-800 text-base text-gray-900 dark:text-white focus:border-black dark:focus:border-white transition-colors bg-transparent leading-relaxed"
                :maxlength="200"
              />
            </view>
         </view>

       </view>
    </scroll-view>

    <!-- Bottom Actions -->
    <view class="fixed bottom-0 inset-x-0 p-6 bg-white/90 dark:bg-black/90 backdrop-blur-xl border-t border-gray-100 dark:border-white/5 z-50">
       <button 
         class="w-full h-14 rounded-full bg-black dark:bg-white text-white dark:text-black font-bold text-lg flex items-center justify-center shadow-lg active:scale-95 transition-all disabled:opacity-50 disabled:scale-100"
         :disabled="!isValid"
         @tap="submit"
       >
         <text v-if="submitting">发布中...</text>
         <text v-else>立即发布</text>
       </button>
    </view>

  </view>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { categoriesService } from '../../services/api';

const imagePath = ref('');
const submitting = ref(false);
const form = ref({
  title: '',
  tags: [],
  description: '',
  category: ''
});

const commonTags = ['Minimalist', 'Nature', 'Cyberpunk', 'Abstract', 'Anime', 'Dark', 'City'];
const categories = ref([]);

onMounted(async () => {
  try {
    const res = await categoriesService.findAll();
    categories.value = res.map(c => c.name);
  } catch (error) {
    console.error('Failed to fetch categories:', error);
  }
});

const isValid = computed(() => {
  return imagePath.value && form.value.title.trim() && form.value.category;
});

const goBack = () => uni.navigateBack();

const chooseImage = () => {
  uni.chooseImage({
    count: 1,
    sizeType: ['original', 'compressed'],
    sourceType: ['album', 'camera'],
    success: (res) => {
      imagePath.value = res.tempFilePaths[0];
    }
  });
};

const toggleTag = (tag) => {
  if (form.value.tags.includes(tag)) {
    form.value.tags = form.value.tags.filter(t => t !== tag);
  } else {
    if (form.value.tags.length >= 5) return;
    form.value.tags.push(tag);
  }
};

const handleCategoryChange = (e) => {
  form.value.category = categories.value[e.detail.value];
};

const submit = () => {
  if (!isValid.value) return;
  submitting.value = true;
  
  uni.uploadFile({
    url: '/api/wallpapers', // Proxied to localhost:3000/wallpapers
    filePath: imagePath.value,
    name: 'file',
    formData: {
      title: form.value.title,
      description: form.value.description,
      categories: form.value.category,
      tags: form.value.tags.join(',')
    },
    success: (uploadFileRes) => {
      if (uploadFileRes.statusCode === 201 || uploadFileRes.statusCode === 200) {
         uni.showToast({ title: '发布成功! 等待审核', icon: 'success' });
         setTimeout(() => {
            uni.switchTab({ url: '/pages/index/index' });
         }, 1500);
      } else {
        uni.showToast({ title: '发布失败', icon: 'none' });
      }
    },
    fail: (err) => {
      console.error(err);
      uni.showToast({ title: '网络错误', icon: 'none' });
    },
    complete: () => {
      submitting.value = false;
    }
  });
};
</script>

// src/pages/Upload.jsx
import { useState, useEffect } from 'react';
import { Upload as UploadIcon, Check, Image as ImageIcon, X, Hash, LayoutGrid, Plus } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function Upload() {
    const navigate = useNavigate();
    const [file, setFile] = useState(null);
    const [preview, setPreview] = useState('');
    const [formData, setFormData] = useState({
        title: '',
        category: '',
        tags: '',
        description: ''
    });
    const [status, setStatus] = useState('idle');
    const [availableCategories, setAvailableCategories] = useState([]);
    const [availableTags, setAvailableTags] = useState([]);

    useEffect(() => {
        const fetchData = async () => {
            try {
                const [catsRes, tagsRes] = await Promise.all([
                    fetch('/api/categories'),
                    fetch('/api/tags')
                ]);
                if (catsRes.ok) {
                    const cats = await catsRes.json();
                    setAvailableCategories(cats);
                    if (cats.length > 0) {
                        setFormData(prev => ({ ...prev, category: cats[0].name }));
                    }
                }
                if (tagsRes.ok) {
                    setAvailableTags(await tagsRes.json());
                }
            } catch (err) {
                console.error('Failed to pre-fetch categories/tags', err);
            }
        };
        fetchData();
    }, []);

    const handleFileChange = (e) => {
        const selectedFile = e.target.files[0];
        if (selectedFile) {
            setFile(selectedFile);
            const reader = new FileReader();
            reader.onloadend = () => setPreview(reader.result);
            reader.readAsDataURL(selectedFile);
        }
    };

    const toggleTag = (name) => {
        const currentTags = formData.tags ? formData.tags.split(',').map(t => t.trim()).filter(Boolean) : [];
        if (currentTags.includes(name)) {
            setFormData({ ...formData, tags: currentTags.filter(t => t !== name).join(',') });
        } else {
            setFormData({ ...formData, tags: [...currentTags, name].join(',') });
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!file) return alert('请先选择图片');
        if (!formData.category) return alert('请选择分类');

        setStatus('loading');
        const data = new FormData();
        data.append('file', file);
        data.append('title', formData.title);
        data.append('category', formData.category);
        data.append('tags', formData.tags);
        data.append('description', formData.description);

        try {
            const res = await fetch('/api/wallpapers', { method: 'POST', body: data });
            if (res.ok) {
                setStatus('success');
                setTimeout(() => navigate('/'), 1500);
            } else {
                setStatus('error');
            }
        } catch (err) {
            setStatus('error');
        }
    };

    return (
        <div className="bg-white min-h-screen pb-20 pt-14 px-4 overflow-y-auto hide-scrollbar">
            <h1 className="text-2xl font-bold text-gray-800 mb-6 flex items-center">
                <UploadIcon className="mr-2" /> 上传发布
            </h1>

            <form onSubmit={handleSubmit} className="space-y-6">
                <div
                    onClick={() => document.getElementById('fileInput').click()}
                    className="w-full h-64 bg-gray-50 rounded-2xl flex items-center justify-center overflow-hidden border-2 border-dashed border-gray-200 relative cursor-pointer active:bg-gray-100 transition shadow-sm"
                >
                    {preview ? (
                        <img src={preview} className="w-full h-full object-cover" />
                    ) : (
                        <div className="text-gray-400 flex flex-col items-center">
                            <UploadIcon size={48} className="mb-2 opacity-20" />
                            <span className="text-sm font-medium">点击上传图片</span>
                        </div>
                    )}
                </div>

                <input id="fileInput" type="file" className="hidden" accept="image/*" onChange={handleFileChange} />

                <div>
                    <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2 px-1">标题</label>
                    <input
                        type="text"
                        required
                        className="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all shadow-sm"
                        placeholder="给作品起个好听的名字..."
                        value={formData.title}
                        onChange={e => setFormData({ ...formData, title: e.target.value })}
                    />
                </div>

                <div className="grid grid-cols-1 gap-4">
                    <div>
                        <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2 px-1">全部分类</label>
                        <div className="flex flex-wrap gap-2">
                            {availableCategories.map(cat => (
                                <button
                                    key={cat.id}
                                    type="button"
                                    onClick={() => setFormData({ ...formData, category: cat.name })}
                                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${formData.category === cat.name
                                        ? 'bg-purple-600 text-white shadow-md scale-105'
                                        : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
                                        }`}
                                >
                                    {cat.name}
                                </button>
                            ))}
                            {availableCategories.length === 0 && (
                                <button type="button" onClick={() => navigate('/settings/categories')} className="text-xs text-purple-600 flex items-center">
                                    <Plus size={14} className="mr-1" /> 去创建分类
                                </button>
                            )}
                        </div>
                    </div>
                </div>

                <div>
                    <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2 px-1">常用标签</label>
                    <div className="flex flex-wrap gap-2 mb-3">
                        {availableTags.map(tag => (
                            <button
                                key={tag.id}
                                type="button"
                                onClick={() => toggleTag(tag.name)}
                                className={`px-3 py-1.5 rounded-full text-xs transition-all border ${formData.tags.split(',').includes(tag.name)
                                    ? 'bg-purple-50 border-purple-200 text-purple-600'
                                    : 'bg-white border-gray-100 text-gray-400 hover:border-purple-100'
                                    }`}
                            >
                                #{tag.name}
                            </button>
                        ))}
                        {availableTags.length === 0 && (
                            <button type="button" onClick={() => navigate('/settings/tags')} className="text-xs text-purple-600 flex items-center">
                                <Plus size={14} className="mr-1" /> 去创建标签
                            </button>
                        )}
                    </div>
                    <input
                        type="text"
                        className="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all shadow-sm text-sm"
                        placeholder="或手动输入标签，用逗号分隔"
                        value={formData.tags}
                        onChange={e => setFormData({ ...formData, tags: e.target.value })}
                    />
                </div>

                <div>
                    <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2 px-1">描述 (可选)</label>
                    <textarea
                        className="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all shadow-sm text-sm h-24 resize-none"
                        placeholder="关于这张图的更多细节..."
                        value={formData.description}
                        onChange={e => setFormData({ ...formData, description: e.target.value })}
                    />
                </div>

                <div className="bg-amber-50 rounded-xl p-4 flex gap-3 items-start border border-amber-100">
                    <div className="w-5 h-5 bg-amber-500 rounded-full flex items-center justify-center shrink-0 mt-0.5 text-white text-[10px] font-bold">!</div>
                    <div className="space-y-1">
                        <p className="text-[11px] font-bold text-amber-900">审核说明</p>
                        <p className="text-[10px] text-amber-700 leading-relaxed">
                            为了维护内容质量，新上传的图片将进入后台审核队列。审核通过后将正式公开展示。
                        </p>
                    </div>
                </div>

                <button
                    disabled={status === 'loading'}
                    className={`w-full py-4 rounded-2xl text-white font-bold text-lg mt-4 flex items-center justify-center transition-all shadow-lg
                        ${status === 'success' ? 'bg-green-500 shadow-green-100' : 'bg-black active:scale-95 shadow-gray-200'}
                        ${status === 'loading' ? 'opacity-70 animate-pulse' : ''}
                    `}
                >
                    {status === 'loading' && '同步数据中...'}
                    {status === 'success' && <><Check className="mr-2" /> 发布成功(待审核)</>}
                    {status === 'idle' && '确认发布'}
                    {status === 'error' && '发布失败，请重试'}
                </button>
            </form>
        </div>
    )
}
